cd /tmp && \
    git clone https://github.com/brendan-rius/jupyter-c-kernel.git && \
    cd /tmp/jupyter-c-kernel && \
    python setup.py install_c_kernel && \
    python -m jupyter-c-kernel.install
